CREATE TABLE users (
  userid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(50) NOT NULL UNIQUE,
  pwd varchar(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  bio varchar(255),
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title varchar(50) NOT NULL,
  image text NOT NULL,
  desc varchar(144) NOT NULL,
  user_id INTEGER references users (userid) ON DELETE CASCADE,
);

CREATE TABLE comments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  desc varchar(144) NOT NULL,
  post_id INTEGER references posts (id) ON DELETE CASCADE,
  user_id INTEGER references users (id) ON DELETE CASCADE
);

CREATE TABLE likes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id INTEGER references posts (id) ON DELETE CASCADE,
  user_id INTEGER references users (userid) ON DELETE CASCADE,
  isLiked BOOLEAN
);
